config/routes.rb
Rails.application.routes.draw do
  resources :records
  root "records#new"

end

app/models/record.rb
class Record < ActiveRecord::Base
  acts_as_xlsx
  enum year: [ "I", "II", "III", "IV" ]
  enum department: [ "CSE","IT" ]
  enum transport: [ "Hosteler","Day-Scholar" ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to root_path, notice: 'Registered Successfully' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
    # redirect_to new_record_path
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:name, :email, :department, :year, :roll_no, :register_no,:transport)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SJIT GNU/Linux Users Group </title>
  <!-- <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Fertigo"> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<container>
<div class="col-md-2">
  <%= image_tag "clglogo.png", size: '150x150' %>
</div>
<div class="col-md-8">
  <center><h2>St. Joseph's Institute of Technology</h2><br>
  <h3>GNU/Linux Users Group</h3></center>
</div>
<div class="col-md-2">
  <%= image_tag "test.png", size: '150x150' %>
</div>
</container>
<!-- <center> -->
<%= yield %>
<!-- </center> -->
<div class= "col-md-6">
<%= link_to "Join our mailing lists","https://www.freelists.org/list/sjitglug", :target => "_blank" %>
</div>
<div class= "col-md-6" align="right">
<footer>
<%= link_to "Blog","http://sjitglug.tumblr.com", :target => "_blank"%>
</footer>
</body>
</html>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name,"Student Name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email,"E-mail Id" %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :department,"Department" %><br>
    <%= f.select :department,options_for_select(Record.departments.map{|x| [x[0], x[0]]}) %>
  </div>
  <div class="field">
    <%= f.label :year,"Year" %><br>
    <%= f.select :year,options_for_select(Record.years.map{|x| [x[0], x[0]]}) %>
  </div>
  <div class="field">
    <%= f.label :roll_no,"Roll No." %><br>
    <%= f.text_field :roll_no %>
  </div>
  <div class="field">
    <%= f.label :register_no,"Register No." %><br>
    <%= f.text_field :register_no %>
  </div>
  <div class="field">
    <%= f.label :transport,"I am a " %><br>
    <%= f.select :transport,options_for_select(Record.transports.map{|x| [x[0], x[0]]}) %>
  </div>
  <div class="actions">
    <%= f.submit :Register %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Records</h1>
Total Count: <%= Record.count %><br>
Individual Count <% a = Record.group(:department).count %>
CSE: <%= a[0] %>
IT: <%= a[1] %><br>
<%= link_to "Export", records_path(format: "xlsx") %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Year</th>
      <th>Roll no</th>
      <th>Register no</th>
      <th>H or D</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.name %></td>
        <td><%= record.email %></td>
        <td><%= record.department %></td>
        <td><%= record.year %></td>
        <td><%= record.roll_no %></td>
        <td><%= record.register_no %></td>
        <td><%= record.transport %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<p id="notice"><%= notice %></p>
<container>
<div class="col-md-5"></div>
<div class="col-md-4">

<h1>Registration</h1>

<%= render 'form' %>
</div>
<%# link_to 'Back', records_path %>
</container>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @record.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @record.email %>
</p>

<p>
  <strong>Department:</strong>
  <%= @record.department %>
</p>

<p>
  <strong>Year:</strong>
  <%= @record.year %>
</p>

<p>
  <strong>Roll no:</strong>
  <%= @record.roll_no %>
</p>

<p>
  <strong>Register no:</strong>
  <%= @record.register_no %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>